services:
  - type: web
    name: axie-colyseus-server
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    envVars:
      - key: NODE_ENV
        value: production
